# Question

The component below makes a mistake when using `useEffect`. When running this code, we will get an error from React!

What is the mistake? Also, please demonstrate how to properly fetch by fixing this code.

```js
const DogDisplay = () => {
  const [imgSrc, setImgSrc] = useState(
    "https://images.dog.ceo/breeds/hound-english/n02089973_612.jpg"
  );

  useEffect(async () => {
    try {
      const response = await fetch("https://dog.ceo/api/breeds/image/random");
      if (!response.ok) throw new Error(`Error: ${response.status}`);
      const data = await response.json();
      setImgSrc(data.message);
    } catch (error) {
      console.error(error);
    }
  }, []);

  return <img src={imgSrc} />;
};
```

# Answer

The mistake here is that we use the async function inside the useEffect function which isn't allowed, if we wanted to format it correctly it would look like so.

```js
const DogDisplay = () => {
 const [imgSrc, setImgSrc] = useState('https://images.dog.ceo/breeds/hound-english/n02089973_612.jpg');

  useEffect(() =>{
    const doFetch = async (() => {
      try {
        const response = await fetch('https://dog.ceo/api/breeds/image/random');
        if (!response.ok) throw new Error(`Error: ${response.status}`)
        const data = await response.json();
        setImgSrc(data.message);
      }catch (error) {
        console.error(error);
      }
    }, []);
  doFetch();
});
return <img src={imgSrc} />
}
```

# Teacher Feedback
2/3
You're correct! However their is an error in your code! You invoked the doFetch function outside of the useEffect event. 